export const PUESTOS: string[] = [
  'Administrador',
  'Agente de ventas',
  'Analista',
  'Asistente administrativo',
  'Automatización',
  'Auxiliar contable',
  'Auxiliar de almacén',
  'Auxiliar de compras',
  'Auxiliar de recursos humanos',
  'Cajero',
  'Coordinador',
  'Director general',
  'Encargado de área',
  'Gerente',
  'Jefe de departamento',
  'Operador',
  'QA',
  'Rack Profile',
  'Recepcionista',
  'Soporte técnico',
  'Supervisor',
  'Técnico',
  'Otro',
]
